# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 701ac123229af4ee41f4cf6c748684cbf7b628169b485c9d0d8b3d599b8895ec764cebed6192be54e2d95bdc264ac831997a8684ba0d70696c77ca95ac54288e

test:
  secret_key_base: f575021b1208bb3d765b2bd1e466777762fcf22d6c5299f7dfaa08b3c66ed55806031a75476503d17d316333d9cebb35eb833a130f056b416b0d4769401abbad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
